name: YogaAsana
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.1
  flutter_gifimage: ^1.0.0
  cached_network_image: ^2.2.0+1
  path_provider: ^1.6.11
  intro_slider: ^2.3.1
  shared_preferences: ^0.5.7+3
  splashscreen: ^1.2.0
  # connectivity: ^0.4.9
  after_layout: ^1.0.7+2
  audio: ^0.0.5
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.2
  # audioplayers: ^0.13.2
  flutter_html: ^1.0.0
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  # firebase_core: ^0.4.0+9
  camera: ^0.5.5
  tflite: ^1.0.4
  percent_indicator: ^2.1.1+1
  # flutter_swiper: ^1.1.6
  image_picker: ^0.6.1+10
  # image_cropper: ^1.2.3
  # flutter_svg: ^0.18.0
  # assets_audio_player: ^2.0.7+9
  # flutter_neumorphic: ^3.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.0.0
  wave: ^0.0.8
  google_fonts:
  json_annotation:
  provider: ^4.0.1
  uuid: ^2.0.4
  mobx:
  flutter_mobx:
  intl: ^0.16.1
  built_collection: ^4.3.2
  wakelock: ^0.1.3+4
  package_info: ^0.4.0+13
  flutter_markdown: ^0.3.3
  flushbar: ^1.10.2
  audioplayers: ^0.14.0
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:
  mobx_codegen:
  logger: ^0.8.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/
    - assets/poses/
    - assets/images/
    - assets/gif/
    - assets/icons/
    - assets/data/
    # - CHANGELOG.md

  
  fonts:

    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
